# Generated by Django 3.1.5 on 2021-02-04 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('evntid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('etype', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('edate', models.DateField()),
                ('etime', models.CharField(max_length=20)),
                ('edesc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
