# Generated by Django 3.1.5 on 2021-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='orgusrname',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='evntid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
