# Generated by Django 3.1.5 on 2021-02-09 01:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0003_auto_20210206_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='evntid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
