# Generated by Django 3.1.5 on 2021-02-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0004_auto_20210209_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('contact', models.FloatField()),
                ('org_no', models.CharField(blank=True, max_length=30, null=True)),
                ('org_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'organiser',
                'managed': True,
            },
        ),
    ]
