# Generated by Django 3.1.5 on 2021-02-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0005_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='prof',
            field=models.FileField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
    ]
