# Generated by Django 3.1.5 on 2021-02-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0006_organiser_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='prof',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
