# Generated by Django 3.1.5 on 2021-02-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0007_auto_20210209_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organiser',
            new_name='Organisers',
        ),
    ]
