# Generated by Django 3.1.5 on 2021-02-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0008_auto_20210209_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evntorganisers',
            fields=[
                ('contact', models.FloatField()),
                ('org_no', models.CharField(blank=True, max_length=30, null=True)),
                ('org_name', models.CharField(blank=True, max_length=30, null=True)),
                ('prof', models.FileField(blank=True, default='media/default.png', null=True, upload_to='media')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evntorganisers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Organisers',
        ),
    ]
