# Generated by Django 3.1.5 on 2021-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0009_auto_20210209_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evntregistrations',
            fields=[
                ('regid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('evntid', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'evntregistrations',
                'managed': True,
            },
        ),
    ]
